package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;

import javafx.scene.layout.VBox;

/**
 * Controller class for the homePage.fxml file.
 * 
 * This class manages the behavior and events of the homePage view. It defines
 * actions for the buttons and handles the navigation to other views. The view
 * displays buttons and images for various albums and provides a search button.
 * The buttons allow navigation to specific album pages or to the logview page.
 * The search button is not implemented yet.
 * 
 * @author Enric&Miriam
 * @version v1
 *
 */
public class homePageController {
	@FXML
	private VBox panelFormSignIn;
	@FXML
	private Button Drake;
	@FXML
	private ImageView Drakeimagen;
	@FXML
	private Button Michael;
	@FXML
	private ImageView Michaelimagen;
	@FXML
	private Button Nirvana;
	@FXML
	private ImageView Nirvanaimagen;
	@FXML
	private Button btnDrake;
	@FXML
	private Button btnMichael;
	@FXML
	private Button btnNirvana;
	@FXML
	private Button btnThriller;
	@FXML
	private ImageView Thriller;
	@FXML
	private Button btnOffTheWall;
	@FXML
	private ImageView OffTheWall;
	@FXML
	private Button btnBad;
	@FXML
	private ImageView Bad;
	@FXML
	private Button btnHonestlyNeverMind;
	@FXML
	private ImageView HonestlyNeverMind;
	@FXML
	private Button btnTooLate;
	@FXML
	private ImageView Too_Late;
	@FXML
	private Button btnNothingWasTheSame;
	@FXML
	private ImageView NothingWasSame;
	@FXML
	private Button btninUtero;
	@FXML
	private ImageView inUteroImagen;
	@FXML
	private Button Bleach;
	@FXML
	private ImageView BleachImagen;
	@FXML
	private Button Nevermind;
	@FXML
	private ImageView NevermindImagen;
	@FXML
	private Button btnSearch;
	@FXML
	private Button btnHome;
	@FXML
	private Button btnExit;

	// Event Listener on Button[#btnDrake].onAction
	/**
	 * Event listener for the Drake button. Loads the albumPageDrake.fxml file and
	 * sets it as the scene. Sets the window title to "MuseME". Shows the
	 * primaryStage.
	 *
	 * @param event The action event triggered by the button.
	 */
	@FXML
	public void actionDrake(ActionEvent event) {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("albumPageDrake.fxml"));
			Scene scene = new Scene(root);
			Main.primaryStage.setTitle("MuseME");
			Main.primaryStage.setScene(scene);
			Main.primaryStage.show();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnMichael].onAction
	/**
	 * Event listener for the Michael button. Loads the albumPageMichael.fxml file
	 * and sets it as the scene. Sets the window title to "MuseME". Shows the
	 * primaryStage.
	 *
	 * @param event The action event triggered by the button.
	 */
	@FXML
	public void actionMichael(ActionEvent event) {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("albumPageMichael.fxml"));
			Scene scene = new Scene(root);
			Main.primaryStage.setTitle("MuseME");
			Main.primaryStage.setScene(scene);
			Main.primaryStage.show();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnNirvana].onAction
	/**
	 * Event listener for the Nirvana button. Loads the albumPageNirvana.fxml file
	 * and sets it as the scene. Sets the window title to "MuseME". Shows the
	 * primaryStage.
	 *
	 * @param event The action event triggered by the button.
	 */
	@FXML
	public void actionNirvana(ActionEvent event) {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("albumPageNirvana.fxml"));
			Scene scene = new Scene(root);
			Main.primaryStage.setTitle("MuseME");
			Main.primaryStage.setScene(scene);
			Main.primaryStage.show();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnThriller].onAction
	@FXML
	public void actionThriller(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnOffTheWall].onAction
	@FXML
	public void actionOffTheWall(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnBad].onAction
	@FXML
	public void actionBad(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnHonestlyNeverMind].onAction
	@FXML
	public void actionHonestlyNeverMind(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnTooLate].onAction
	@FXML
	public void actionTooLate(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnNothingWasTheSame].onAction
	@FXML
	public void actionNothingWasTheSame(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btninUtero].onAction
	@FXML
	public void actioninUtero(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#Bleach].onAction
	@FXML
	public void actionBleach(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#Nevermind].onAction
	@FXML
	public void actionNevermind(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnSearch].onAction
	/**
	 * Event listener for the search button. Loads the logview.fxml file and sets it
	 * as the scene. Sets the window title to "MuseME". Shows the primaryStage.
	 *
	 * @param event The action event triggered by the button.
	 */
	@FXML
	public void actionSearch(ActionEvent event) {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("logview.fxml"));
			Scene scene = new Scene(root);
			Main.primaryStage.setTitle("MuseME");
			Main.primaryStage.setScene(scene);
			Main.primaryStage.show();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnHome].onAction
	/**
	 * Event listener for the home button. Loads the homePage.fxml file and sets it
	 * as the scene. Sets the window title to "MuseME". Shows the primaryStage.
	 *
	 * @param event The action event triggered by the button.
	 */
	@FXML
	public void actionHome(ActionEvent event) {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("homePage.fxml"));
			Scene scene = new Scene(root);
			Main.primaryStage.setTitle("MuseME");
			Main.primaryStage.setScene(scene);
			Main.primaryStage.show();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#btnExit].onAction
	/**
	 * Event listener for the exit button. Closes the primaryStage.
	 *
	 * @param event The action event triggered by the button.
	 */
	@FXML
	public void actionExit(ActionEvent event) {

		Main.primaryStage.close();
	}
}
